### PR TITLE
Add Bullseye '_11'  dockers

### PR DESCRIPTION
**Pull request by ArcEye**

### CODE REVIEW

**Comment by zultron** [comment]
@ArcEye I'm pretty sure if we merge the top two commits 5902f6b and b55b36b, it will break building the `machinekit-cnc` repository, since it doesn't pull in deps from that repo.

I don't remember how those got in there, but I'm sure I'm to blame.  Very sorry.

Could you rebase or otherwise get those out of this PR?

**Comment by zultron** [comment]
I do have this fixed in [another branch][1], but it introduces another problem:  commit 39968e2efbc91336e372a11548bdb94be514a0b2 switches to the `libreadline-gplv2-dev` package to be compatible with LCNC.  This could cause problems for a small subset of people, so I don't want to merge it without getting more feedback first.

[1]: https://github.com/zultron/mk-cross-builder/commits/master

**Comment by ArcEye** [comment]
Just add or remove whatever you want @zultron 
Those commits are only there because you wanted them in

**Comment by zultron** [comment]
Fair enough, @ArcEye, and thanks for playing along as far as you did.

**Pull request closed without merging**
